#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-maven-model
Version  : 2.0.5
Release  : 6
URL      : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.5/maven-model-2.0.5.jar
Source0  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.5/maven-model-2.0.5.jar
Source1  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.10/maven-model-2.0.10.jar
Source2  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.10/maven-model-2.0.10.pom
Source3  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.11/maven-model-2.0.11.jar
Source4  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.11/maven-model-2.0.11.pom
Source5  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.jar
Source6  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.pom
Source7  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.5/maven-model-2.0.5.pom
Source8  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.jar
Source9  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.pom
Source10  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.7/maven-model-2.0.7.jar
Source11  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.7/maven-model-2.0.7.pom
Source12  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.8/maven-model-2.0.8.pom
Source13  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.jar
Source14  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.pom
Source15  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.0/maven-model-2.0.pom
Source16  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.jar
Source17  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.pom
Source18  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.jar
Source19  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.pom
Source20  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.jar
Source21  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.pom
Source22  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.0.5/maven-model-3.0.5.jar
Source23  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.0.5/maven-model-3.0.5.pom
Source24  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.0/maven-model-3.0.jar
Source25  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.0/maven-model-3.0.pom
Source26  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.jar
Source27  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.pom
Source28  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.6.0/maven-model-3.6.0.jar
Source29  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.6.0/maven-model-3.6.0.pom
Source30  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.6.1/maven-model-3.6.1.jar
Source31  : https://repo1.maven.org/maven2/org/apache/maven/maven-model/3.6.1/maven-model-3.6.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-maven-model-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-maven-model package.
Group: Data

%description data
data components for the mvn-maven-model package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.5
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.5/maven-model-2.0.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.10
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.10/maven-model-2.0.10.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.10
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.10/maven-model-2.0.10.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.11
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.11/maven-model-2.0.11.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.11
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.11/maven-model-2.0.11.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.4
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.4
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.5
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.5/maven-model-2.0.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.6
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.6
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.7
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.7/maven-model-2.0.7.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.7
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.7/maven-model-2.0.7.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.8
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.8/maven-model-2.0.8.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.9
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.9
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0/maven-model-2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.0
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.0
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.1
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.1
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.4
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.4
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.5
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.5/maven-model-3.0.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.5
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.5/maven-model-3.0.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0/maven-model-3.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0/maven-model-3.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.3.9
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.3.9
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.0
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.0/maven-model-3.6.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.0
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.0/maven-model-3.6.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.1
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.1/maven-model-3.6.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.1
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.1/maven-model-3.6.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.10/maven-model-2.0.10.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.10/maven-model-2.0.10.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.11/maven-model-2.0.11.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.11/maven-model-2.0.11.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.4/maven-model-2.0.4.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.5/maven-model-2.0.5.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.5/maven-model-2.0.5.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.6/maven-model-2.0.6.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.7/maven-model-2.0.7.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.7/maven-model-2.0.7.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.8/maven-model-2.0.8.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0.9/maven-model-2.0.9.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.0/maven-model-2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.0/maven-model-2.2.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/2.2.1/maven-model-2.2.1.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.4/maven-model-3.0.4.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.5/maven-model-3.0.5.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0.5/maven-model-3.0.5.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0/maven-model-3.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.0/maven-model-3.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.3.9/maven-model-3.3.9.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.0/maven-model-3.6.0.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.0/maven-model-3.6.0.pom
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.1/maven-model-3.6.1.jar
/usr/share/java/.m2/repository/org/apache/maven/maven-model/3.6.1/maven-model-3.6.1.pom
